apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.name }}
  namespace: fpsa
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      imagePullSecrets:
      - name: regcred
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: "docker.pkg.github.com/federation-purple-study-associations/fpsa-cron-statistics/cron-statistics:{{ .Values.tag }}"
            name: {{ .Values.name }}
            env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db
                  key: DB_NAME