name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build docker image
      run: docker build . --file Dockerfile --tag svfpsa/cron-statistics:$GITHUB_SHA
      
    - name: Login to Docker Hub
      env:
        Username: ${{secrets.DOCKER_USERNAME}}
        Password: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $Username -p $Password
      
    - name: Publish docker image
      run: docker push svfpsa/cron-statistics:$GITHUB_SHA

    - name: Deploy
      uses: 'deliverybot/helm@master'
      with:
        release: 'fpsa-cron-statistics'
        namespace: 'fpsa'
        chart: 'k8b'
        token: '${{ github.token }}'
        values: |
          tag: $GITHUB_SHA
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
