name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login
      run: docker login docker.pkg.github.com -u bastiaanv -p ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/federation-purple-study-associations/fpsa-cron-database-backup/cron-statistics:$GITHUB_SHA

    - name: Publish docker image
      run: docker push docker.pkg.github.com/federation-purple-study-associations/fpsa-cron-database-backup/cron-statistics:$GITHUB_SHA

    - name: Deploy
      uses: 'deliverybot/helm@master'
      with:
        release: 'fpsa-cron-statistics'
        namespace: 'fpsa'
        chart: 'k8b'
        helm: 'helm3'
        token: '${{ github.token }}'
        values: |
          tag: '${{ github.sha }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
